services:
  postgres:
    image: postgres:16
    container_name: ai-postgres

    environment:
      POSTGRES_DB: ai_sonar_fix_assistant
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres

    ports:
      - "5432:5432"

    volumes:
      - postgres_data:/var/lib/postgresql/data


  sonarqube:
    image: sonarqube:community
    container_name: ai-sonarqube
    depends_on:
      - postgres
    ports:
      - "9000:9000"
    environment:
      SONAR_ES_BOOTSTRAP_CHECKS_DISABLE: "true"


volumes:
  postgres_data:
